export const ROUTE = 'ROUTE';

export const BOOTSTRAP_VERSION = 'BOOTSTRAP_VERSION';
export const BOOTSTRAP_START = 'BOOTSTRAP_START';
export const BOOTSTRAP_ERROR = 'BOOTSTRAP_ERROR';
export const BOOTSTRAP_SUCCESS = 'BOOTSTRAP_SUCCESS';
export const RETRY_BOOTSTRAP = 'RETRY_BOOTSTRAP';

export const DOWNLOADING = 'DOWNLOADING';
export const DOWNLOADED = 'DOWNLOADED';
export const INSTALLING = 'INSTALLING';
export const INSTALLED = 'INSTALLED';

export const RUNTIME_READY = 'RUNTIME_READY';
export const RUNTIME_STARTED = 'RUNTIME_STARTED';
export const RUNTIME_ERROR = 'RUNTIME_ERROR';
export const RUNTIME_STARTING = 'RUNTIME_STARTING';
export const RUNTIME_STOPPED = 'RUNTIME_STOPPED';

export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_SCRIPT = 'CHANGE_SCRIPT';

export const EXECUTE_SCRIPT_SUCCESS = 'EXECUTE_SCRIPT_SUCCESS';
export const EXECUTE_SCRIPT_START = 'EXECUTE_SCRIPT_START';
export const MERGE_SCRIPT_START = 'MERGE_SCRIPT_START';
export const KEVSCRIPT_ERROR = 'KEVSCRIPT_ERROR';
export const MERGE_SCRIPT_SUCCESS = 'MERGE_SCRIPT_SUCCESS';
export const CHANGE_CTX_VARS = 'CHANGE_CTX_VARS';
export const CHANGE_MODEL = 'CHANGE_MODEL';

export const DEPLOY_START = 'DEPLOY_START';
export const DEPLOY_ERROR = 'DEPLOY_ERROR';
export const DEPLOY_SUCCESS = 'DEPLOY_SUCCESS';

export const REGISTRY_HOST = 'REGISTRY_HOST';
export const REGISTRY_PORT = 'REGISTRY_PORT';
export const REGISTRY_SSL = 'REGISTRY_SSL';
export const RESOLVER = 'RESOLVER';

export const LOG = 'LOG';
export const POP_LOG = 'POP_LOG';
export const LOG_UNREAD = 'LOG_UNREAD';
export const CLEAR_LOGS = 'CLEAR_LOGS';
